# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'iOSTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PlayKit_IMA', :path => '..'

  target 'iOSTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Needed from Xcode 14, supports from iOS 11, need to update pods with lowest supported value.
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
    end
  end
end
