# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'iOSTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PlayKit_IMA', :path => '..'
  pod 'PlayKit', :git => 'https://github.com/kaltura/playkit-ios.git', :branch => 'develop'

  target 'iOSTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSTestAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
