# Uncomment the next line to define a global platform for your project
platform :tvos, '9.1'

target 'tvOSTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'PlayKit_IMA/tvOS', :path => '..'
#pod 'GoogleAds-IMA-tvOS-SDK', '4.2.1'

end

#post_install do |installer|
#    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
#        configuration.build_settings['ARCHS'] = 'arm64'
#    end
#end
